In [7]:
import pandas as pd

people=pd.read_csv('C:/LOCAL_PEOPLE_GU_2020.csv',encoding='euc-kr',index_col=False)
map_code=pd.read_csv('C:/법정동.csv',encoding='euc-kr',index_col=False)

In [17]:
people_data = people.drop(['기준일ID','시간대구분']),axis=1)

In [15]:
map_code_data=map_code.drop_duplicates('시군구코드')

In [16]:
map_code_data

      시군구코드      시  시군구명       동      동2
0     11740  서울특별시   강동구     상일동   상일제1동
2     11290  서울특별시   성북구     돈암동   정릉제1동
3     11530  서울특별시   구로구      항동      항동
4     11305  서울특별시   강북구     수유동    수유1동
10    11410  서울특별시  서대문구     대현동    북아현동
11    11500  서울특별시   강서구     공항동   방화제1동
15    11440  서울특별시   마포구     공덕동     염리동
16    11710  서울특별시   송파구     장지동     위례동
20    11230  서울특별시  동대문구     전농동  답십리제1동
22    11140  서울특별시    중구     신당동     약수동
29    11110  서울특별시   종로구     와룡동     혜화동
31    11350  서울특별시   노원구     공릉동    공릉1동
36    11680  서울특별시   강남구     신사동    압구정동
51    11620  서울특별시   관악구     신림동     신사동
52    11560  서울특별시  영등포구  영등포동1가    영등포동
67    11590  서울특별시   동작구      본동  노량진제1동
93    11200  서울특별시   성동구     옥수동     옥수동
103   11170  서울특별시   용산구   용산동5가    한강로동
123   11380  서울특별시   은평구     역촌동     역촌동
149   11215  서울특별시   광진구     노유동   자양제4동
150   11260  서울특별시   중랑구     망우동    망우본동
324   11545  서울특별시   금천구     가산동     NaN
388   11320  서울특별시   도봉구     방학동   방학제4동
425   11650  서울특별시   서초구     양재동   양재제1동
486   11470  서울특별시   양천구     신정동    신정7동
1846  11000  서울특별시   NaN   서울특별시     NaN

In [21]:
df=pd.merge(people_data,map_code_data,left_on='자치구코드',right_on='시군구코드')

In [23]:
df_data=df.drop(['시군구코드'],axis=1)

In [25]:
df_data

        자치구코드       총생활인구수      시 시군구명    동     동2
0       11110  248283.0355  서울특별시  종로구  와룡동    혜화동
1       11110  223410.1830  서울특별시  종로구  와룡동    혜화동
2       11110  218505.7015  서울특별시  종로구  와룡동    혜화동
3       11110  215724.8573  서울특별시  종로구  와룡동    혜화동
4       11110  214702.3265  서울특별시  종로구  와룡동    혜화동
...       ...          ...    ...  ...  ...    ...
219595  11740  511093.3303  서울특별시  강동구  상일동  상일제1동
219596  11740  516376.5926  서울특별시  강동구  상일동  상일제1동
219597  11740  519720.9150  서울특별시  강동구  상일동  상일제1동
219598  11740  523144.8586  서울특별시  강동구  상일동  상일제1동
219599  11740  524891.9605  서울특별시  강동구  상일동  상일제1동

[219600 rows x 6 columns]

In [27]:
data=pd.pivot_table(df_data,index=['자치구코드','시군구명'],aggfunc='sum')

In [28]:
data.to_csv('2020.csv', encoding=cp949)

                  총생활인구수
자치구코드 시군구명
11110 종로구   2.420484e+09
11140 중구    2.218879e+09
11170 용산구   2.491271e+09
11200 성동구   3.009586e+09
11215 광진구   3.226628e+09
11230 동대문구  3.120200e+09
11260 중랑구   3.162280e+09
11290 성북구   3.754145e+09
11305 강북구   2.668427e+09
11320 도봉구   2.475458e+09
11350 노원구   4.628147e+09
11380 은평구   3.948586e+09
11410 서대문구  3.160764e+09
11440 마포구   3.986391e+09
11470 양천구   3.506790e+09
11500 강서구   4.760585e+09
11530 구로구   3.420235e+09
11545 금천구   1.965451e+09
11560 영등포구  4.010552e+09
11590 동작구   3.471770e+09
11620 관악구   4.280152e+09
11650 서초구   5.010212e+09
11680 강남구   7.071819e+09
11710 송파구   6.571526e+09
11740 강동구   4.428900e+09